# Generated by Django 5.2 on 2025-04-05 00:41

import django.db.models.deletion
import orden.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenID', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[(orden.models.OrdenStatus['CREATED'], 'CREADO'), (orden.models.OrdenStatus['PAYED'], 'PAGADO'), (orden.models.OrdenStatus['COMPLETED'], 'COMPLETADO'), (orden.models.OrdenStatus['CANCELED'], 'CANCELADO')], default=orden.models.OrdenStatus['CREATED'], max_length=40)),
                ('envio_total', models.DecimalField(decimal_places=2, default=10, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
            ],
        ),
    ]
