# Generated by Django 4.2 on 2025-03-31 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orden.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_cart_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(orden.models.OrdenStatus['CREATED'], 'CREADO'), (orden.models.OrdenStatus['PAYED'], 'PAGADO'), (orden.models.OrdenStatus['COMPLETED'], 'COMPLETADO'), (orden.models.OrdenStatus['CANCELED'], 'CANCELADO')], default=orden.models.OrdenStatus['CREATED'], max_length=40)),
                ('envio_total', models.DecimalField(decimal_places=2, default=10, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
