# Generated by Django 4.2 on 2025-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='envio_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=9),
        ),
    ]
