# Generated by Django 4.2 on 2025-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_alter_orden_envio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ordenID',
            field=models.CharField(default='s', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
