# Generated by Django 5.2 on 2025-04-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_orden_promo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='envio_total',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9),
        ),
    ]
