# Generated by Django 5.2 on 2025-04-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto'),
        ),
        migrations.AddField(
            model_name='cart',
            name='producto',
            field=models.ManyToManyField(through='carts.CartProduct', to='web.producto'),
        ),
    ]
