# Generated by Django 4.2 on 2025-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cliente_profile'),
        ('carts', '0002_remove_cart_producto_cart_fee_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='producto',
            field=models.ManyToManyField(through='carts.CartProduct', to='web.producto'),
        ),
    ]
