# Generated by Django 4.2 on 2025-03-21 19:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_producto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True),
        ),
    ]
