# Generated by Django 4.2 on 2025-03-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fechar_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ManyToManyField(to='web.producto')),
            ],
        ),
    ]
