# Generated by Django 4.2 on 2025-03-25 02:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='titulo', unique=True),
            preserve_default=False,
        ),
    ]
