"""
Django settings for Webtienda project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lm*h8n6-zi(lao5l4dqh3bsp=d9q(gc9b%)i8uw*nzmp+5+uln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'carts',
    'orden',
    'DirEnvio',
]

JAZZMIN_SETTINGS = {
    "site_title": "Panel de Tienda",
    "site_header": "Administración de la Tienda",
    "site_brand": "Mi Tienda",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "Mi Tienda © 2025",
    "search_model": "web.Producto",  # Puedes cambiarlo a tu modelo

    # Logos / Íconos (opcional, si quieres usar imágenes)
    "site_logo": None,  # o 'static/img/logo.png' si tienes uno
    "site_icon": None,  # o 'static/img/favicon.ico'

    # Colores
    "primary_color": "#0d6efd",  # Azul (puedes usar cualquier hex)

    # Menú izquierdo (opcionalmente ordenado)
    "order_with_respect_to": ["web.Categoria", "web.Producto"],

    # Comportamiento
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # Puedes ocultar apps si quieres
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Webtienda.urls'

AUTH_USER_MODEL = 'web.User'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.categorias_disponibles',
                'carts.context_processors.cart',
                'web.context_processors.year_context',               
            ],
        },
    },
]

WSGI_APPLICATION = 'Webtienda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tiendaweb',
        'USER': 'julio',
        'PASSWORD': 'riverplate',
        'HOST': 'localhost',  # Cambia si usas un servidor remoto
        'PORT': '3306',       # Puerto por defecto para MySQL        
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Activa la localización
USE_L10N = True
USE_THOUSAND_SEPARATOR = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "web/static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

