# Generated by Django 5.2 on 2025-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea1', models.CharField(max_length=300)),
                ('linea2', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=300)),
                ('postal_codigo', models.CharField(max_length=10)),
                ('default', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
