# Generated by Django 4.2 on 2025-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirEnvio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
